### ISSUE TITLE
the analysis of dependencies of Zipkin didn't work

### ISSUE THREAD

**Issue by minlywang** [jhipster/jhipster-console#107]
I created a microservice project using jhipster and jhipster console.
In the jhipster-zipkin I can find the traces in the view of  "Find a trace" but I can't view the dependecies in the view of "Dependencies".

**Comment by PierreBesson** [comment]
It's because you have to start the run-job.sh script (in the container, see: https://github.com/jhipster/jhipster-console/blob/master/run-zipkin-dependency-job.sh). I actually made a cron to launch this automatically but I think it is broken. The right approach would be to introduce a "batch job" container based on the zipkin/zipkin-dependency docker image.

**Comment by minlywang** [comment]
Could you specify the steps in details or waiting for you to fix it?

**Comment by PierreBesson** [comment]
@minlywang put the `run-zipkin-dependency-job.sh` which is in this repo in the same folder as the `docker-compose.yml` file and run it.

**Comment by minlywang** [comment]
It's working... Thanks
