### ISSUE TITLE
[FEATURE] Log forwarding from a file

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#20]
Some people are concerned with lower performance when using a socket connection from their app and would rather have a separate agent read from log files.

We could use either logstash or filebeat for this task.

**Comment by pascalgrimaud** [comment]
On the main generator, if the user choose ELK, maybe we can ask him how he wants to monitor all his apps?

It's just an idea, I think there is some work for this.

**Comment by jdubois** [comment]
No that would be against 12 factors -> they need to use the console output, maybe we should add some documentation about this.

**Comment by PierreBesson** [comment]
After thinking about it for some time. It seems this approach has too many downsides (for example, it needs an agent per app so it's complicated with docker deployment) and the setup we have now with logback encoder seems to work fine with what seems to be acceptable loss of performance.

So I won't be adding this feature in the next future.

**Comment by ygokirmak** [comment]
@PierreBesson we are using filebeat for logforwarding instead of socket appender. Filebeat agents are triggered on container startup and they save their last checkpoints ( registries ) within application folder so on container restart we don't duplicate logs. 

We choose this method bec we are generating reports via ELK dashboards and don't want data loss. 

just wrote fyi..

**Comment by PierreBesson** [comment]
@ygokirmak Filebeat is also an interesting approach but we are unlikely to switch to it.
Still, I would be quite interested to see your config, especially if it can be setup simply with docker-compose.
