### ISSUE TITLE
docker-compose up fail to start logstash

### ISSUE THREAD

**Issue by nodje** [jhipster/jhipster-console#26]
During the startup process after `docker-compose up` from the project's root, the only log for logstash is the following:

`elk-logstash_1       | {:timestamp=>"2016-04-21T03:54:54.466000+0000", :message=>"translation missing: en.logstash.runner.configuration.file-not-found", :level=>:error}
jhipsterconsole_elk-logstash_1 exited with code 1`

and consequently, only `jhipster-console` and `elk-elasticsearch` are started.

**Comment by nodje** [comment]
I got it working on a different docker machine though. 
`elk-logstash_1       | {:timestamp=>"2016-04-21T08:27:42.569000+0000", :message=>"Pipeline main started"}`

I leave it up to you to close close the issue. Let me know if you want more info about the case.

**Comment by PierreBesson** [comment]
Thanks for reporting the issue. I think it might be related to a known problem that docker on mac and windows can only mount folder under the user directory.

Does your issue relates to this: https://github.com/jhipster/jhipster-console/issues/17 ?

**Comment by nodje** [comment]
Oddly, it failed when ran on Docker on native Linux and now runs ok on OS X.
I've ran `docker-compose` wihout changing a line from the latest commit.

**Comment by nodje** [comment]
On another OSX machine, I have the same problem.
I noticed at the beginning of the startup log:
`ERROR: for elk-logstash  mkdir /Users/nodje: protocol error`

The thing is I start the docker containers on another remote machine, not locally.
I do `export DOCKER_HOST=192.168.3.254:2376` for instance, then `docker-compose up elk-logstash`
It works if I am on the local OSX machine (or any type I'd guess, as long as it's local) but not if i am on a remote machine. 

This is clearly the source of the problem, but I don't understand what's causing it in the `docker-compose.yml`. I'd wager it comes from the `volumes` as it's the only potential source causing the problem.

**Comment by PierreBesson** [comment]
Yes the issue comes from volumes. Did you try to `docker exec -it` into your container and see if you can see logstash.conf there.

OK, I have not yet done something like you do with a remote docker host but I remember a colleague telling me that to deal with multiple host on docker compose you should setup an `overlay` network as the default `bridge` network is does not support having multiple hosts. Anyway I might be wrong about this and this is a bit beyond the scope of what is supported by JHipster for now.

If you don't manage to make it work, I suggest you copy the docker-compose.yml and other required files on your remote machine and startup docker-compose from there. It should work.

**Comment by nodje** [comment]
It does work with a "classic" docker usage, no worries.
