### ISSUE TITLE
 Service 'jhipster-console' failed to build: The command '/bin/sh -c kibana plugin --install elastic/timelion' returned a non-zero code: 70

### ISSUE THREAD

**Issue by hsdj-alex** [jhipster/jhipster-console#30]
Hi,
I execute  docker-compose up and I receive the following errors:
ERROR: Service 'jhipster-console' failed to build: The command '/bin/sh -c kibana plugin --install elastic/timelion' returned a non-zero code: 70
Many thanks for this project.

**Comment by PierreBesson** [comment]
It is also failing for me at this step now. I don't understand because in the past it worked. I will investigate the issue.

In the meantime please use the [bootstrap instruction](https://github.com/jhipster/jhipster-console/tree/master/bootstrap) to use the image from docker hub instead of building it yourself. It will become be the recommended way to start the console, I just need to update the documentation.

**Comment by hsdj-alex** [comment]
Thank you very much for your help. It cost me a whole day to find the environment configuration issues.Now, it works perfectly.
