### ISSUE TITLE
Webhooks on certain conditions

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-console#33]
Is that possible to have a way to configure webhooks for certain conditions to help scale the infrastructure? CPU levels, network bandwidth usage, number of requests, jvm heap size...

**Comment by PierreBesson** [comment]
Well, you could try to implement this with [Elastalert](http://elastalert.readthedocs.io/en/latest/) which is already integrated with the console. It should not be difficult to be writing your own [custom alerter in Python](https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py). Recently someone PR some [Gitter integration code](https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L739) that seems to be similar to what you want.

I think that it would actually be very nice because the alerts that would allow to scale out could be triggered by a *spike rule* in elastalert. Similarly, the alert to scale down could be triggered by a *flatline* rule. 

I didn't have time to dig more into using Elastalert but trying to do an autoscaler with it would be amazing !

**Comment by marcelinobadin** [comment]
Cool. I will dive into this. I read that Elastalert integrates with AWS SNS and this is pretty good because from the SNS I can trigger a AWS Lambda code for example to run some code and scale up or down my containers and services

**Comment by PierreBesson** [comment]
@marcelinobadin Have you succeeded in implementing your idea ? I'm thinking of closing this issue if we don't have time to pursue this.

**Comment by PierreBesson** [comment]
I'm closing this issue as this is a matter of configuring Elastalert to use your favorite alerting method (cf http://elastalert.readthedocs.io/en/latest/ruletypes.html#alerts).
