### ISSUE TITLE
When I Start Console Show 'start ES failed'

### ISSUE THREAD

**Issue by huiqiangyang** [jhipster/jhipster-console#47]
when I start jhipster-console by docker use 'docker-componse up' show this exception:
``` 
jhipster-elasticsearch_1  | [2016-12-25T05:55:46,338][INFO ][o.e.b.BootstrapCheck     ] [Z_PTvLl] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
jhipster-elasticsearch_1  | ERROR: bootstrap checks failed
```
who can tell me reason,thanks~

**Comment by PierreBesson** [comment]
@huiqiangyang I just checked and I don't have this error. If you are using the docker-compose.yml file at the root of this repo, maybe you have problems building the docker image correctly. Then try to use our prebuilt image published on docker-hub.

Make sure that you are using this one : https://github.com/jhipster/jhipster-console/blob/master/bootstrap/docker-compose.yml

**Comment by huiqiangyang** [comment]
@PierreBesson  Thank you, I`m sure my docker-compose.yml from your git,and I not edit this file, only run `docker-componse -f docker-compose.yml up` then from log I see ES start faild, up show is error. Now this error I not have  solve, I may be need your help

**Comment by PierreBesson** [comment]
Sorry I cannot help you more as you didn't give me any information about your configuration. Are you on Windows using the legacy docker toolbox ? Then you would need to change your docker_compose files as you cannot use localhost in your docker container. See our website, it is documented here.
Otherwise I have no idea what else could be the problem..

**Comment by huiqiangyang** [comment]
@PierreBesson OK ,thank you .My system is Ubuntu docker run is well
