### ISSUE TITLE
Cannot upgrade to elastic v5.2.2

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#49]
Kibana is blank when upgrading, it might be related to our script to create the logstash-* index.

**Comment by ygokirmak** [comment]
I think the problem is related to x-pack.
When you open kibana, it makes request to elasticsearch to get default-index,
elasticsearch returns 404 to this request although index exists and show blank screen (https://github.com/elastic/kibana/issues/9028)

I checked elasticsearch logs and seems kibana user does not have permission to get details of default-index;
working request;
`curl -XGET "localhost:9200/logstash-*/_mapping/field/*?ignore_unavailable=false&allow_no_indices=false&include_defaults=true" -u elastic:changeme` 

not working request;
`curl -XGET "localhost:9200/logstash-*/_mapping/field/*?ignore_unavailable=false&allow_no_indices=false&include_defaults=true" -u kibana:changeme`

disabling x-pack seems solving the problem
