### ISSUE TITLE
Visualizations fail with monolith app

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-console#7]
Because they look for the field instance_id that is only sent with micro-services
Shouldn't we base on app_name.raw instead ? This would make the visualizations available for monolith apps and even multi-monolith (app1 monolith and app2 monolith monitored by the same ELK).

**Comment by PierreBesson** [comment]
It's just that this dashboard was intented for micro-services.
The reason why I chose instanceId instead of app_name is because we want to identify which instance of a particuliar app was failing (as a microservice can be replicated many times). But as all instances have the same code, it might be useless to distinguish between the different instances for the default dashboard...

We can change the field to app_name so that it will also work for monoliths.

**Comment by cbornet** [comment]
No, you're right : in a "cluster" or multi-node pre service MSA, we cannot rely on the app_name.
What if we used the host IP ?
Or maybe it's not the same thing to monitor a MSA and a monolith so it shouldn't be done on the same dashboards...

**Comment by PierreBesson** [comment]
OK, so let's do specific dashboard for microservices. Maybe we can set a rule that every visualization or dashboard that can be used only with microservices must have "microservices" in its name.

Yes you can also use host+port but you would lose information on which app it is.

**Comment by cbornet** [comment]
We could have a unique identifier field produced by logstash. Something like ${app_name)-${host}-${port}

**Comment by PierreBesson** [comment]
Yes ! I guess it would actually be better than the instanceId as we would
immediately know where to find the app. Currently we need to check on
Eureka on which host and port we can find the app.

Le ven. 11 mars 2016 22:13, Christophe Bornet <notifications@github.com> a
écrit :
